# Generated by Django 5.2.7 on 2025-10-06 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('category', models.CharField(choices=[('business', 'Для бизнеса'), ('industry', 'Для промышленности'), ('city', 'Безопасный город'), ('housing', 'Для жилых комплексов'), ('general', 'Общая консультация')], default='general', max_length=20, verbose_name='Категория')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('consent', models.BooleanField(default=False, verbose_name='Согласие на обработку данных')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка на консультацию',
                'verbose_name_plural': 'Заявки на консультацию',
                'ordering': ['-created_at'],
            },
        ),
    ]
