# Generated by Django 5.2.7 on 2025-10-10 18:35

from django.db import migrations
import os
from django.conf import settings
from django.core.files import File

IMAGE_DATA = {
    'home_hero': 'photo-1558494949-ef010cbdcc31.jpg',
    'home_problem_city': 'ob.jpg',
    'home_problem_business': 'photo-1460925895917-afdab827c52f.jpg',
    'home_problem_housing': 'photo-1545324418-cc1a3fa10c00.jpg',
    'home_solution_ai': 'cyber-brain-scaled.jpg',
    'business_hero': 'photo-1556761175-b413da4baf72.jpg',
    'business_solution_1': 'photo-1581091226825-a6a2a5aee158.jpg',
    'business_solution_2': 'photo-1454165804606-c3d57bc86b40.jpg',
    'business_solution_3': 'photo-1553413077-190dd305871c.jpg',
    'business_solution_4': 'photo-1504328345606-18bbc8c9d7d1.jpg',
    'business_solution_5': 'photo-1441986300917-64674bd600d8.jpg',
    'business_solution_6': 'photo-1558002038-1055907df827.jpg',
    'industry_hero': 'photo-1581094794329-c8112a89af12.jpg',
    'industry_solution_1': 'photo-1581092795360-fd1ca04f0952.jpg',
    'industry_solution_2': 'photo-1513828583688-c52646db42da.jpg',
    'industry_solution_3': 'photo-1516321318423-f06f85e504b3.jpg',
    'industry_solution_4': 'photo-1621905251189-08b45d6a269e.jpg',
    'industry_solution_5': 'photo-1504868584819-f8e8b4b6d7e3.jpg',
    'industry_solution_6': 'photo-1454165804606-c3d57bc86b40.jpg',
    'city_hero': 'photo-1449824913935-59a10b8d2000.jpg',
    'city_solution_1': 'b4d7b2de5362a0160a142eb1d865f4e7.jpg',
    'city_solution_2': '3_0.jpg',
    'city_solution_3': '0ad431bc8e76f6463dbaf23dc9082476.jpg',
    'city_solution_4': '2022.06.03-1654245782.2415_sam-70473.jpg',
    'housing_hero': 'photo-1486406146926-c627a92ad1ab.jpg',
    'housing_solution_1': 'photo-1590674899484-d5640e854abe.jpg',
    'housing_solution_2': '_b593010a-1afc-4d48-9c50-22e5e3872b091.max-800x1200.jpg',
    'housing_solution_3': 'photo-1545324418-cc1a3fa10c00.jpg',
    'housing_solution_4': 'photo-1503454537195-1dcabb73ffb9.jpg',
    'housing_solution_5': 'photo-1516321318423-f06f85e504b3.jpg',
    'cta_background': 'photo-1550751827-4bd374c3f58b.jpg',
    'contacts_hero': 'photo-1556761175-b413da4baf72.jpg',
}

def populate_images(apps, schema_editor):
    SiteImage = apps.get_model('main', 'SiteImage')
    images_path = os.path.join(settings.BASE_DIR, 'static', 'images', 'photo')

    for key, filename in IMAGE_DATA.items():
        image_path = os.path.join(images_path, filename)
        if os.path.exists(image_path):
            with open(image_path, 'rb') as f:
                SiteImage.objects.create(
                    key=key,
                    description=f'Image for {key}',
                    image=File(f, name=filename)
                )

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_siteimage'),
    ]

    operations = [
        migrations.RunPython(populate_images),
    ]
