# Generated by Django 5.2.7 on 2025-10-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_populate_site_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-адрес (slug)')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('content', models.TextField(verbose_name='Содержимое страницы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Текстовая страница',
                'verbose_name_plural': 'Текстовые страницы',
            },
        ),
    ]
