# Generated by Django 5.2.7 on 2025-10-11 00:30

from django.db import migrations
import os
from django.conf import settings
from django.core.files import File

def update_home_solution_image(apps, schema_editor):
    SiteImage = apps.get_model('main', 'SiteImage')
    images_path = os.path.join(settings.BASE_DIR, 'static', 'images', 'photo')
    
    # Обновляем изображение для home_solution_ai
    try:
        obj = SiteImage.objects.get(key='home_solution_ai')
        new_image_path = os.path.join(images_path, 'cyber-brain-scaled.jpg')
        if os.path.exists(new_image_path):
            with open(new_image_path, 'rb') as f:
                obj.image = File(f, name='cyber-brain-scaled.jpg')
                obj.save()
                print('Updated home_solution_ai image to cyber-brain-scaled.jpg')
    except SiteImage.DoesNotExist:
        print('SiteImage with key home_solution_ai not found')

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_populate_text_pages'),
    ]

    operations = [
        migrations.RunPython(update_home_solution_image),
    ]