# Generated by Django 5.2.7 on 2025-10-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_update_home_solution_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteimage',
            options={'ordering': ['page', 'display_name'], 'verbose_name': 'Изображение сайта', 'verbose_name_plural': 'Изображения сайта'},
        ),
        migrations.AddField(
            model_name='siteimage',
            name='display_name',
            field=models.CharField(default='', max_length=200, verbose_name='Понятное название'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='page',
            field=models.CharField(choices=[('home', 'Главная'), ('business', 'Для бизнеса'), ('industry', 'Для промышленности'), ('city', 'Безопасный город'), ('housing', 'Для ЖК'), ('contacts', 'Контакты'), ('common', 'Общие')], default='common', max_length=20, verbose_name='Страница'),
        ),
    ]
