# Generated by Django 5.2.7 on 2025-10-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_siteimage_options_siteimage_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
            ],
            options={
                'verbose_name': 'Изображение бизнеса',
                'verbose_name_plural': 'Изображения бизнеса',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.siteimage',),
        ),
        migrations.CreateModel(
            name='CityImage',
            fields=[
            ],
            options={
                'verbose_name': 'Изображение города',
                'verbose_name_plural': 'Изображения города',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.siteimage',),
        ),
        migrations.CreateModel(
            name='CommonImage',
            fields=[
            ],
            options={
                'verbose_name': 'Общее изображение',
                'verbose_name_plural': 'Общие изображения',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.siteimage',),
        ),
        migrations.CreateModel(
            name='ContactsImage',
            fields=[
            ],
            options={
                'verbose_name': 'Изображение контактов',
                'verbose_name_plural': 'Изображения контактов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.siteimage',),
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
            ],
            options={
                'verbose_name': 'Изображение главной',
                'verbose_name_plural': 'Изображения главной',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.siteimage',),
        ),
        migrations.CreateModel(
            name='HousingImage',
            fields=[
            ],
            options={
                'verbose_name': 'Изображение ЖК',
                'verbose_name_plural': 'Изображения ЖК',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.siteimage',),
        ),
        migrations.CreateModel(
            name='IndustryImage',
            fields=[
            ],
            options={
                'verbose_name': 'Изображение промышленности',
                'verbose_name_plural': 'Изображения промышленности',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.siteimage',),
        ),
    ]
