# Generated by Django 5.2.7 on 2025-10-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_businessimage_cityimage_commonimage_contactsimage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessImage',
        ),
        migrations.DeleteModel(
            name='CityImage',
        ),
        migrations.DeleteModel(
            name='CommonImage',
        ),
        migrations.DeleteModel(
            name='ContactsImage',
        ),
        migrations.DeleteModel(
            name='HomeImage',
        ),
        migrations.DeleteModel(
            name='HousingImage',
        ),
        migrations.DeleteModel(
            name='IndustryImage',
        ),
    ]
