# Generated by Django 5.2.7 on 2025-10-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_businessimage_delete_cityimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
